name = "preCOPSE"
uuid = "d9b5de2a-7974-4db9-baf2-bb5265170031"
authors = ["Minmin Fu <mjfu@g.harvard.edu>", "Mark Baum <markmbaum@protonmail.com>"]
version = "0.1.0"

[deps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
